import React from 'react';
import Link from 'next/link';
import WebsiteCard from './WebsiteCard'
import { ArrowRight, Star, TrendingUp, Clock } from 'lucide-react';
import { mockWebsites } from '../data/mockData'

const DiscoverySection = () => {
  const newWebsites = mockWebsites.slice(0, 6);
  const featuredWebsites = mockWebsites.filter(w => w.isFeatured).slice(0, 6);
  const popularWebsites = [...mockWebsites].sort((a, b) => b.visitCount - a.visitCount).slice(0, 6);

  const Section = ({ title, description, icon: Icon, websites, linkPath, gradient }: any) => (
    <div className="mb-16">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
        <div className="mb-4 sm:mb-0">
          <div className="flex items-center space-x-3 mb-2">
            <div className={`p-2 rounded-lg ${gradient}`}>
              <Icon className="w-5 h-5 text-white" />
            </div>
            <h3 className="text-2xl font-bold text-white">{title}</h3>
          </div>
          <p className="text-gray-400">{description}</p>
        </div>
        <Link
          href={linkPath}
          className="inline-flex items-center space-x-2 text-purple-400 hover:text-purple-300 font-medium transition-colors group"
        >
          <span>See All</span>
          <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
        </Link>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {websites.map((website: any) => (
          <WebsiteCard key={website.id} website={website} />
        ))}
      </div>
    </div>
  );

  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8">
      <div className="container mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Discover Amazing Crypto Projects
          </h2>
          <p className="text-lg text-gray-300 max-w-2xl mx-auto">
            Explore the latest websites created by our AI, featuring innovative crypto projects from around the world
          </p>
        </div>

        <Section
          title="New Websites"
          description="Latest websites generated by our AI"
          icon={Clock}
          websites={newWebsites}
          linkPath="/directory?sort=newest"
          gradient="bg-gradient-to-r from-blue-600 to-blue-700"
        />

        <Section
          title="Featured Projects"
          description="Handpicked projects showcasing innovation"
          icon={Star}
          websites={featuredWebsites}
          linkPath="/directory?filter=featured"
          gradient="bg-gradient-to-r from-yellow-600 to-yellow-700"
        />

        <Section
          title="Popular Websites"
          description="Most visited projects this week"
          icon={TrendingUp}
          websites={popularWebsites}
          linkPath="/directory?sort=popular"
          gradient="bg-gradient-to-r from-green-600 to-green-700"
        />
      </div>
    </section>
  );
};

export default DiscoverySection;